# Generated by Django 4.2 on 2023-06-30 11:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SYS_EMAIL_CODE',
            fields=[
                ('ID', models.CharField(max_length=30, primary_key=True, serialize=False)),
                ('CODE', models.IntegerField()),
                ('TYPE', models.CharField(max_length=10)),
                ('EXPIRE', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='SYS_LOG',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('CREATE_TIME_PY', models.IntegerField(null=True)),
                ('CREATE_TIME', models.DateField(null=True)),
                ('ERROR', models.CharField(max_length=10, null=True)),
                ('TYPE', models.CharField(max_length=10)),
                ('MSG', models.CharField(max_length=100, null=True)),
                ('USER_ID', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='SYS_USER',
            fields=[
                ('ID', models.IntegerField(primary_key=True, serialize=False)),
                ('LOGIN_NAME', models.CharField(max_length=100)),
                ('PASSWORD', models.CharField(max_length=100)),
                ('USER_TYPE', models.IntegerField()),
                ('SEX', models.IntegerField(null=True)),
                ('BORN_TIME', models.DateField(null=True)),
                ('CREATE_TIME', models.IntegerField()),
                ('ERROR_COUNT', models.IntegerField()),
                ('STATUS', models.IntegerField()),
                ('LOCK_TIME', models.IntegerField(null=True)),
                ('OCCUPATION', models.CharField(max_length=10, null=True)),
                ('EMAIL', models.CharField(max_length=30)),
                ('AVATAR', models.BinaryField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='SYS_USER_TOKEN',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('TOKEN', models.CharField(max_length=16)),
                ('ID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='knowledgegraph_django_model.sys_user')),
            ],
        ),
        migrations.CreateModel(
            name='SYS_USER_NAME',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('NAME', models.CharField(max_length=50)),
                ('TEL', models.CharField(max_length=30)),
                ('CARD_TYPE', models.CharField(max_length=10)),
                ('IDCARD', models.CharField(max_length=50)),
                ('ID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='knowledgegraph_django_model.sys_user')),
            ],
        ),
        migrations.CreateModel(
            name='SYS_USER_IP',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('CN_IP', models.CharField(max_length=30, null=True)),
                ('FG_IP', models.CharField(max_length=30, null=True)),
                ('IP', models.CharField(max_length=30)),
                ('ID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='knowledgegraph_django_model.sys_user')),
            ],
        ),
        migrations.CreateModel(
            name='SYS_USER_FEEDBACK',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('CREATE_TIME', models.IntegerField()),
                ('TYPE', models.CharField(max_length=10)),
                ('MSG', models.TextField()),
                ('IMG_0', models.BinaryField(null=True)),
                ('IMG_1', models.BinaryField(null=True)),
                ('IMG_2', models.BinaryField(null=True)),
                ('IMG_3', models.BinaryField(null=True)),
                ('ID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='knowledgegraph_django_model.sys_user')),
            ],
        ),
    ]
