# Generated by Django 4.2 on 2023-07-21 03:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agriculture_knowledgegraph_django_model', '0003_remove_sys_user_feedback_id_remove_sys_user_ip_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sys_email_code',
            name='SEND_TIMESTAMP',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='sys_user',
            name='CREATE_TIME',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='sys_user_feedback',
            name='CREATE_TIME',
            field=models.CharField(max_length=20),
        ),
    ]
